# BASE_NAME is the name of the base image e.g. base-tidyverse
ARG BASE_NAME
# FAASR_VERSION FaaSr version to install from - this must match a tag in the GitHub repository e.g. 1.1.2
ARG FAASR_VERSION
# FAASR_INSTALL_REPO is tha name of the user's GitHub repository to install FaaSr from e.g. janedoe/FaaSr-Package-dev
ARG FAASR_INSTALL_REPO

# Start from specified base image
FROM $BASE_NAME:$FAASR_VERSION


# Install FaaSr from specified repo and tag
#RUN Rscript -e "args <- commandArgs(trailingOnly=TRUE); library(devtools); install_github(paste0(args[1],'@',args[2]),force=TRUE)" $FAASR_INSTALL_REPO $FAASR_VERSION
RUN Rscript -e "args <- commandArgs(trailingOnly=TRUE); library(devtools); install_github(paste0(args[1],'@',args[2]),force=TRUE)" FaaSr/FaaSr-Package 1.1.2

# OpenWhisk specifics
CMD ["/bin/bash","-c","cd actionProxy && python3 actionproxy.py"]
